import type {
  CelebrationCategory,
  Collection,
  Illustration,
  PersonalizationTemplate,
  ProductType,
} from "./types";

/* ---------------------------------------------------------------------------
   Local catalogue — source of truth for development, fallback when Supabase
   is not configured, and the origin of supabase/seed.sql.

   Image files live under public/illustrations/<slug>/.
   `placeholder: true` marks artwork whose original file has not been
   delivered yet (see docs/ASSETS.md for the one-command swap).
--------------------------------------------------------------------------- */

const img = (slug: string) => ({
  card: `/illustrations/${slug}/card.webp`,
  full: `/illustrations/${slug}/full.webp`,
});

export const personalizationTemplates: PersonalizationTemplate[] = [
  {
    id: "naissance",
    name: { fr: "Naissance", en: "Birth" },
    fields: [
      {
        key: "babyName",
        type: "text",
        label: { fr: "Prénom du bébé", en: "Baby’s name" },
        placeholder: { fr: "Inès", en: "Ines" },
        required: true,
        maxLength: 20,
        showInPreview: true,
      },
      {
        key: "birthDate",
        type: "date",
        label: { fr: "Date de naissance", en: "Date of birth" },
        required: false,
        showInPreview: true,
      },
      {
        key: "birthTime",
        type: "time",
        label: { fr: "Heure", en: "Time" },
        required: false,
      },
      {
        key: "weight",
        type: "text",
        label: { fr: "Poids", en: "Weight" },
        placeholder: { fr: "3,250 kg", en: "3.25 kg" },
        required: false,
        maxLength: 12,
      },
      {
        key: "height",
        type: "text",
        label: { fr: "Taille", en: "Height" },
        placeholder: { fr: "49 cm", en: "49 cm" },
        required: false,
        maxLength: 12,
      },
      {
        key: "presetMessage",
        type: "select",
        label: { fr: "Un petit mot tout prêt", en: "A ready-made note" },
        required: false,
        options: [
          {
            value: "bienvenue-petit-tresor",
            label: { fr: "Bienvenue petit trésor", en: "Welcome little one" },
          },
          {
            value: "bienvenue-petite-fille",
            label: { fr: "Bienvenue petite fille", en: "Welcome baby girl" },
          },
          {
            value: "bienvenue-petit-garcon",
            label: { fr: "Bienvenue petit garçon", en: "Welcome baby boy" },
          },
          {
            value: "bienvenue-petit-ange",
            label: { fr: "Bienvenue petit ange", en: "Welcome sweet angel" },
          },
          {
            value: "bienvenue-dans-la-famille",
            label: {
              fr: "Bienvenue dans la famille",
              en: "Welcome to the family",
            },
          },
          {
            value: "bonjour-petit-soleil",
            label: { fr: "Bonjour petit soleil", en: "Hello little sunshine" },
          },
        ],
        showInPreview: true,
      },
      {
        key: "customMessage",
        type: "textarea",
        label: { fr: "Ou votre propre message", en: "Or your own message" },
        required: false,
        maxLength: 120,
      },
    ],
  },
  {
    id: "anniversaire",
    name: { fr: "Anniversaire", en: "Birthday" },
    fields: [
      {
        key: "name",
        type: "text",
        label: { fr: "Prénom", en: "Name" },
        placeholder: { fr: "Léa", en: "Lea" },
        required: true,
        maxLength: 20,
        showInPreview: true,
      },
      {
        key: "age",
        type: "number",
        label: { fr: "Âge", en: "Age" },
        required: false,
        min: 1,
        max: 120,
        showInPreview: true,
      },
      {
        key: "message",
        type: "textarea",
        label: { fr: "Votre message d’anniversaire", en: "Your birthday message" },
        placeholder: {
          fr: "Joyeux anniversaire, petite abeille !",
          en: "Happy birthday, little bee!",
        },
        required: false,
        maxLength: 120,
        showInPreview: true,
      },
    ],
  },
  {
    id: "douceur",
    name: { fr: "Petit mot doux", en: "Sweet note" },
    fields: [
      {
        key: "firstName",
        type: "text",
        label: { fr: "Prénom", en: "First name" },
        placeholder: { fr: "Inès", en: "Ines" },
        required: true,
        maxLength: 20,
        showInPreview: true,
      },
      {
        key: "presetMessage",
        type: "select",
        label: { fr: "Un petit mot tout prêt", en: "A ready-made note" },
        required: false,
        options: [
          { value: "merci", label: { fr: "Merci", en: "Thank you" } },
          {
            value: "pense-a-toi",
            label: { fr: "Je pense à toi", en: "Thinking of you" },
          },
          {
            value: "plein-de-douceur",
            label: { fr: "Plein de douceur", en: "A hug in a bee" },
          },
          {
            value: "tu-es-mon-soleil",
            label: { fr: "Tu es mon soleil", en: "You are my sunshine" },
          },
        ],
        showInPreview: true,
      },
      {
        key: "message",
        type: "textarea",
        label: { fr: "Ou votre propre message", en: "Or your own message" },
        required: false,
        maxLength: 80,
        showInPreview: true,
      },
      {
        key: "date",
        type: "date",
        label: { fr: "Une date à retenir", en: "A date to remember" },
        required: false,
      },
    ],
  },
];

export const products: ProductType[] = [
  {
    id: "prod-mug",
    slug: "mug",
    name: { fr: "Mug en céramique", en: "Ceramic mug" },
    description: {
      fr: "Un mug tout doux pour les matins câlins, imprimé des deux côtés.",
      en: "A soft-hearted mug for cosy mornings, printed on both sides.",
    },
    personalizable: true,
    order: 1,
    variants: [
      {
        id: "mug-325",
        name: { fr: "325 ml", en: "11 oz" },
        priceCents: 1690,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
      {
        id: "mug-450",
        name: { fr: "450 ml", en: "15 oz" },
        priceCents: 1890,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
  {
    id: "prod-affiche",
    slug: "affiche",
    name: { fr: "Affiche d’art", en: "Art print" },
    description: {
      fr: "Papier mat épais 200 g, couleurs douces et fidèles.",
      en: "Thick 200 gsm matte paper, soft and faithful colours.",
    },
    personalizable: true,
    order: 2,
    variants: [
      {
        id: "affiche-a4",
        name: { fr: "A4 · 21 × 29,7 cm", en: "A4 · 8.3 × 11.7 in" },
        priceCents: 1490,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
      {
        id: "affiche-a3",
        name: { fr: "A3 · 29,7 × 42 cm", en: "A3 · 11.7 × 16.5 in" },
        priceCents: 1990,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
      {
        id: "affiche-30x40",
        name: { fr: "30 × 40 cm", en: "12 × 16 in" },
        priceCents: 2290,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
  {
    id: "prod-carte",
    slug: "carte",
    name: { fr: "Carte double & enveloppe", en: "Greeting card & envelope" },
    description: {
      fr: "Une carte à écrire, à offrir, à garder longtemps.",
      en: "A card to write, to give, to keep for a long time.",
    },
    personalizable: true,
    order: 3,
    variants: [
      {
        id: "carte-a6",
        name: { fr: "A6 · pliée", en: "A6 · folded" },
        priceCents: 490,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
  {
    id: "prod-stickers",
    slug: "stickers",
    name: { fr: "Planche de stickers", en: "Sticker sheet" },
    description: {
      fr: "Des petites abeilles à coller partout où il manque de la douceur.",
      en: "Little bees to stick wherever softness is missing.",
    },
    personalizable: false,
    order: 4,
    variants: [
      {
        id: "stickers-a5",
        name: { fr: "A5", en: "A5" },
        priceCents: 690,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
      {
        id: "stickers-a4",
        name: { fr: "A4", en: "A4" },
        priceCents: 990,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
  {
    id: "prod-tote",
    slug: "tote",
    name: { fr: "Tote bag en coton bio", en: "Organic cotton tote bag" },
    description: {
      fr: "Pour emporter un peu de son petit monde partout avec soi.",
      en: "To carry a piece of her little world everywhere.",
    },
    personalizable: false,
    order: 5,
    variants: [
      {
        id: "tote-unique",
        name: { fr: "38 × 42 cm", en: "15 × 16.5 in" },
        priceCents: 1990,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
  {
    id: "prod-carnet",
    slug: "carnet",
    name: { fr: "Carnet ligné", en: "Lined notebook" },
    description: {
      fr: "128 pages pour les listes, les rêves et les petits riens.",
      en: "128 pages for lists, dreams and lovely little nothings.",
    },
    personalizable: true,
    order: 6,
    variants: [
      {
        id: "carnet-a5",
        name: { fr: "A5 · 128 pages", en: "A5 · 128 pages" },
        priceCents: 1490,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
  {
    id: "prod-body",
    slug: "body",
    name: { fr: "Body bébé en coton bio", en: "Organic cotton baby bodysuit" },
    description: {
      fr: "Tout doux pour la peau des tout-petits, certifié coton biologique.",
      en: "Extra soft on tiny skin, certified organic cotton.",
    },
    personalizable: true,
    order: 7,
    variants: [
      {
        id: "body-3-6",
        name: { fr: "3–6 mois", en: "3–6 months" },
        priceCents: 2290,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
      {
        id: "body-6-12",
        name: { fr: "6–12 mois", en: "6–12 months" },
        priceCents: 2290,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
  {
    id: "prod-coussin",
    slug: "coussin",
    name: { fr: "Coussin douillet", en: "Cosy cushion" },
    description: {
      fr: "Le coussin sur lequel Mademoiselle l’Abeille aime se reposer.",
      en: "The very cushion Mademoiselle l’Abeille likes to rest on.",
    },
    personalizable: false,
    order: 8,
    variants: [
      {
        id: "coussin-40",
        name: { fr: "40 × 40 cm", en: "16 × 16 in" },
        priceCents: 2790,
        printify: { blueprintId: null, printProviderId: null, variantId: null },
        available: true,
      },
    ],
  },
];

export const collections: Collection[] = [
  {
    id: "col-jaune",
    slug: "la-vie-en-jaune",
    name: "La vie en jaune",
    subtitle: {
      fr: "Le monde du miel et des matins lumineux",
      en: "The world of honey and luminous mornings",
    },
    description: {
      fr: "Des jaunes de miel, de paille et de soleil doux : la couleur d’origine de Mademoiselle l’Abeille, celle des jours qui commencent bien.",
      en: "Honey, straw and gentle sunshine yellows: Mademoiselle l’Abeille’s original colour, the colour of days that start well.",
    },
    accent: "#E3B351",
    tint: "#FAF0D8",
    coverIllustrationSlug: "abeille-sereine",
    order: 1,
  },
  {
    id: "col-rose",
    slug: "la-vie-en-rose",
    name: "La vie en rose",
    subtitle: {
      fr: "Tendresse, câlins et joues roses",
      en: "Tenderness, hugs and rosy cheeks",
    },
    description: {
      fr: "Des roses poudrés et des cœurs légers, pour dire l’affection sans grands discours.",
      en: "Powdery pinks and light hearts, to express affection without long speeches.",
    },
    accent: "#C98781",
    tint: "#F7E9E6",
    coverIllustrationSlug: "petite-abeille-curieuse",
    order: 2,
  },
  {
    id: "col-vert",
    slug: "la-vie-en-vert",
    name: "La vie en vert",
    subtitle: {
      fr: "Respirer, s’étirer, se poser",
      en: "Breathe, stretch, settle",
    },
    description: {
      fr: "Des verts d’eucalyptus et de prairie calme, pour les instants de yoga, de repos et de nature.",
      en: "Eucalyptus and quiet-meadow greens, for yoga moments, rest and nature.",
    },
    accent: "#9DB18C",
    tint: "#E4EBDD",
    coverIllustrationSlug: "abeille-trois-ballons",
    order: 3,
  },
  {
    id: "col-bleu",
    slug: "la-vie-en-bleu",
    name: "La vie en bleu",
    subtitle: {
      fr: "Berceuses et ciels tranquilles",
      en: "Lullabies and tranquil skies",
    },
    description: {
      fr: "Des bleus de layette et de ciel d’été, tout indiqués pour les naissances et les chambres d’enfants.",
      en: "Layette and summer-sky blues, made for births and children’s bedrooms.",
    },
    accent: "#8FB4CC",
    tint: "#EAF2F7",
    coverIllustrationSlug: "abeille-ballon-bleu",
    order: 4,
  },
];

export const celebrations: CelebrationCategory[] = [
  {
    id: "cel-naissance",
    slug: "naissance",
    name: { fr: "Naissance", en: "Birth" },
    description: {
      fr: "Souhaiter la bienvenue avec un prénom, une date, un premier souvenir.",
      en: "Say welcome with a name, a date, a very first keepsake.",
    },
    icon: "🍼",
    tint: "#EAF2F7",
    order: 1,
  },
  {
    id: "cel-anniversaire",
    slug: "anniversaire",
    name: { fr: "Anniversaire", en: "Birthday" },
    description: {
      fr: "Des bougies, des ballons et une abeille qui apporte le gâteau.",
      en: "Candles, balloons, and a bee arriving with the cake.",
    },
    icon: "🎂",
    tint: "#FAF0D8",
    order: 2,
  },
  {
    id: "cel-amitie",
    slug: "amitie",
    name: { fr: "Amitié", en: "Friendship" },
    description: {
      fr: "Pour celles et ceux qui rendent la vie plus douce, simplement.",
      en: "For the people who simply make life softer.",
    },
    icon: "🤝",
    tint: "#F7E9E6",
    order: 3,
  },
  {
    id: "cel-remerciement",
    slug: "remerciement",
    name: { fr: "Remerciement", en: "Thank you" },
    description: {
      fr: "Un merci qui se garde : maîtresses, nounous, voisins au grand cœur.",
      en: "A thank-you to keep: teachers, nannies, big-hearted neighbours.",
    },
    icon: "🌼",
    tint: "#FAF0D8",
    order: 4,
  },
  {
    id: "cel-amour",
    slug: "amour",
    name: { fr: "Amour", en: "Love" },
    description: {
      fr: "Des mots doux illustrés, à offrir sans occasion particulière.",
      en: "Illustrated sweet nothings, no special occasion required.",
    },
    icon: "💗",
    tint: "#F7E9E6",
    order: 5,
  },
  {
    id: "cel-yoga",
    slug: "yoga-bien-etre",
    name: { fr: "Yoga & bien-être", en: "Yoga & well-being" },
    description: {
      fr: "Respirer, s’étirer, sourire : la douceur comme discipline.",
      en: "Breathe, stretch, smile: softness as a practice.",
    },
    icon: "🧘",
    tint: "#E4EBDD",
    order: 6,
  },
  {
    id: "cel-attentions",
    slug: "petites-attentions",
    name: { fr: "Petites attentions", en: "Small kindnesses" },
    description: {
      fr: "Parce que les petites choses ont une grande valeur.",
      en: "Because small things hold great value.",
    },
    icon: "🎁",
    tint: "#FAF0D8",
    order: 7,
  },
];

const ALL_SUPPORTS = [
  "mug",
  "affiche",
  "carte",
  "stickers",
  "tote",
  "carnet",
  "coussin",
];

export const illustrations: Illustration[] = [
  {
    id: "ill-abeille-sereine",
    slug: "abeille-sereine",
    title: { fr: "L’Abeille sereine", en: "The Serene Bee" },
    description: {
      fr: "Les yeux fermés, le sourire tranquille : Mademoiselle l’Abeille savoure l’instant présent. Une invitation à respirer, tout simplement.",
      en: "Eyes closed, a quiet smile: Mademoiselle l’Abeille savours the present moment. An invitation to simply breathe.",
    },
    image: {
      src: img("abeille-sereine").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Petite abeille aquarellée aux yeux fermés et au sourire paisible, entourée d’étoiles dorées sur fond jaune pâle",
        en: "Small watercolour bee with closed eyes and a peaceful smile, surrounded by golden sparkles on a pale yellow background",
      },
      background: "#FBF7DC",
      placeholder: false,
    },
    collections: ["la-vie-en-jaune"],
    celebrations: ["yoga-bien-etre", "petites-attentions"],
    tags: [
      { fr: "calme", en: "calm" },
      { fr: "sérénité", en: "serenity" },
      { fr: "yoga", en: "yoga" },
      { fr: "méditation", en: "meditation" },
      { fr: "jaune", en: "yellow" },
      { fr: "douceur", en: "softness" },
    ],
    featured: true,
    featuredOrder: 1,
    personalizationTemplateId: "douceur",
    productSlugs: ALL_SUPPORTS,
    status: "published",
  },
  {
    id: "ill-petite-abeille-curieuse",
    slug: "petite-abeille-curieuse",
    title: { fr: "La Petite Curieuse", en: "The Little Curious One" },
    description: {
      fr: "Debout sur ses petites pattes, l’œil pétillant, elle semble demander : « Et aujourd’hui, on découvre quoi ? »",
      en: "Standing on her little legs, eyes sparkling, she seems to ask: “So, what are we discovering today?”",
    },
    image: {
      src: img("petite-abeille-curieuse").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Petite abeille aquarellée debout, aux grands yeux curieux et joues roses, sur fond rose très pâle",
        en: "Small watercolour bee standing with big curious eyes and rosy cheeks on a very pale pink background",
      },
      background: "#F9EFEA",
      placeholder: true,
    },
    collections: ["la-vie-en-rose"],
    celebrations: ["petites-attentions", "amitie"],
    tags: [
      { fr: "curiosité", en: "curiosity" },
      { fr: "rose", en: "pink" },
      { fr: "enfance", en: "childhood" },
      { fr: "malice", en: "mischief" },
    ],
    featured: true,
    featuredOrder: 2,
    personalizationTemplateId: "douceur",
    productSlugs: ALL_SUPPORTS,
    status: "published",
  },
  {
    id: "ill-abeille-anniversaire-gateau",
    slug: "abeille-anniversaire-gateau",
    title: { fr: "Le Gâteau de fête", en: "The Birthday Cake" },
    description: {
      fr: "Nœud rouge à pois, gâteau aux fraises et nuée de ballons : quand Mademoiselle l’Abeille fête un anniversaire, elle ne fait pas les choses à moitié.",
      en: "Polka-dot bow, strawberry cake and a flurry of balloons: when Mademoiselle l’Abeille celebrates a birthday, she doesn’t do things by halves.",
    },
    image: {
      src: img("abeille-anniversaire-gateau").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Abeille aquarellée portant un nœud rouge à pois, tenant un gâteau aux fraises, entourée de ballons pastel",
        en: "Watercolour bee wearing a red polka-dot bow, holding a strawberry cake, surrounded by pastel balloons",
      },
      background: "#FBF7DC",
      placeholder: true,
    },
    collections: ["la-vie-en-jaune", "la-vie-en-rose"],
    celebrations: ["anniversaire"],
    tags: [
      { fr: "anniversaire", en: "birthday" },
      { fr: "gâteau", en: "cake" },
      { fr: "ballons", en: "balloons" },
      { fr: "fête", en: "party" },
      { fr: "fraise", en: "strawberry" },
    ],
    featured: true,
    featuredOrder: 3,
    personalizationTemplateId: "anniversaire",
    productSlugs: ALL_SUPPORTS,
    status: "published",
  },
  {
    id: "ill-abeille-pot-de-miel",
    slug: "abeille-pot-de-miel",
    title: { fr: "Le Pot de miel", en: "The Honey Jar" },
    description: {
      fr: "Son trésor entre les pattes, elle l’offre à qui sait lire les petites étiquettes. Ajoutez-y un prénom : le miel n’en sera que plus doux.",
      en: "Her treasure held tight, offered to anyone who reads little labels. Add a name — the honey only gets sweeter.",
    },
    image: {
      src: img("abeille-pot-de-miel").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Abeille aquarellée souriante tenant un pot de miel avec une étiquette « Miel » et un prénom calligraphié",
        en: "Smiling watercolour bee holding a honey jar with a “Miel” label and a hand-lettered first name",
      },
      background: "#FFFFFF",
      placeholder: true,
    },
    collections: ["la-vie-en-jaune"],
    celebrations: ["naissance", "petites-attentions", "remerciement"],
    tags: [
      { fr: "miel", en: "honey" },
      { fr: "prénom", en: "name" },
      { fr: "personnalisé", en: "personalized" },
      { fr: "cadeau", en: "gift" },
    ],
    featured: true,
    featuredOrder: 4,
    personalizationTemplateId: "douceur",
    productSlugs: ALL_SUPPORTS,
    status: "published",
  },
  {
    id: "ill-abeille-trois-ballons",
    slug: "abeille-trois-ballons",
    title: { fr: "L’Envolée aux trois ballons", en: "Three-Balloon Flight" },
    description: {
      fr: "Un ballon soleil, un ballon prairie, un ballon tendresse — et la voilà partie livrer de la joie, quelque part où l’on en manque.",
      en: "A sunshine balloon, a meadow balloon, a tenderness balloon — and off she goes, delivering joy wherever it’s running low.",
    },
    image: {
      src: img("abeille-trois-ballons").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Abeille aquarellée s’envolant avec trois ballons orange, vert et rose sur fond crème",
        en: "Watercolour bee flying away with three balloons — orange, green and pink — on a cream background",
      },
      background: "#FBF7DC",
      placeholder: true,
    },
    collections: ["la-vie-en-vert", "la-vie-en-jaune"],
    celebrations: ["anniversaire", "amitie"],
    tags: [
      { fr: "ballons", en: "balloons" },
      { fr: "joie", en: "joy" },
      { fr: "vert", en: "green" },
      { fr: "envol", en: "flight" },
    ],
    featured: true,
    featuredOrder: 5,
    personalizationTemplateId: "anniversaire",
    productSlugs: ALL_SUPPORTS,
    status: "published",
  },
  {
    id: "ill-bebe-abeille",
    slug: "bebe-abeille",
    title: { fr: "Bébé Abeille", en: "Baby Bee" },
    description: {
      fr: "Toute ronde, toute neuve, avec ses ailes à pois : la plus petite habitante de la ruche vient d’arriver — et elle a déjà conquis tout le monde.",
      en: "Perfectly round, brand new, with polka-dot wings: the hive’s tiniest resident has just arrived — and already won everyone over.",
    },
    image: {
      src: img("bebe-abeille").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Bébé abeille aquarellé tout rond aux ailes bleu pâle à pois, sur fond crème",
        en: "Round watercolour baby bee with pale-blue polka-dot wings on a cream background",
      },
      background: "#FBF7DC",
      placeholder: true,
    },
    collections: ["la-vie-en-bleu", "la-vie-en-jaune"],
    celebrations: ["naissance"],
    tags: [
      { fr: "bébé", en: "baby" },
      { fr: "naissance", en: "birth" },
      { fr: "chambre d’enfant", en: "nursery" },
      { fr: "bleu", en: "blue" },
    ],
    featured: true,
    featuredOrder: 6,
    personalizationTemplateId: "naissance",
    productSlugs: [...ALL_SUPPORTS, "body"],
    status: "published",
  },
  {
    id: "ill-abeille-ballon-bleu",
    slug: "abeille-ballon-bleu",
    title: { fr: "Le Ballon bleu", en: "The Blue Balloon" },
    description: {
      fr: "Un seul ballon, mais choisi avec soin : bleu comme un ciel de berceuse. Parfait pour annoncer ou célébrer l’arrivée d’un petit garçon.",
      en: "Just one balloon, but carefully chosen: blue as a lullaby sky. Perfect to announce or celebrate a little boy’s arrival.",
    },
    image: {
      src: img("abeille-ballon-bleu").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Abeille aquarellée souriante à côté d’un ballon bleu aquarelle, sur fond bleu layette",
        en: "Smiling watercolour bee beside a blue watercolour balloon on a layette-blue background",
      },
      background: "#DDEBF5",
      placeholder: true,
    },
    collections: ["la-vie-en-bleu"],
    celebrations: ["naissance", "anniversaire"],
    tags: [
      { fr: "ballon", en: "balloon" },
      { fr: "bleu", en: "blue" },
      { fr: "garçon", en: "boy" },
      { fr: "naissance", en: "birth" },
    ],
    featured: false,
    featuredOrder: null,
    personalizationTemplateId: "naissance",
    productSlugs: [...ALL_SUPPORTS, "body"],
    status: "published",
  },
  {
    id: "ill-les-petites-abeilles",
    slug: "les-petites-abeilles",
    title: { fr: "Les Petites Abeilles", en: "The Little Bees" },
    description: {
      fr: "Cinq humeurs d’abeille sur une même planche : rêveuse, joyeuse, timide, câline, espiègle. Impossible de choisir ? Prenez-les toutes.",
      en: "Five bee moods on a single sheet: dreamy, joyful, shy, cuddly, mischievous. Can’t choose? Take them all.",
    },
    image: {
      src: img("les-petites-abeilles").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Planche de cinq petites abeilles aquarellées dans différentes poses et expressions",
        en: "Sheet of five small watercolour bees in different poses and expressions",
      },
      background: "#FFFFFF",
      placeholder: true,
    },
    collections: ["la-vie-en-jaune"],
    celebrations: ["petites-attentions"],
    tags: [
      { fr: "stickers", en: "stickers" },
      { fr: "planche", en: "sheet" },
      { fr: "expressions", en: "expressions" },
      { fr: "collection", en: "set" },
    ],
    featured: false,
    featuredOrder: null,
    personalizationTemplateId: null,
    productSlugs: ["stickers", "affiche", "carte", "carnet"],
    status: "published",
  },
  {
    id: "ill-quatre-coeurs",
    slug: "quatre-petits-coeurs",
    title: { fr: "Quatre Petits Cœurs", en: "Four Little Hearts" },
    description: {
      fr: "Un câlin d’abeilles, un cœur serré tout contre soi, une révérence fleurie : quatre manières illustrées de dire « je t’aime bien, tu sais ».",
      en: "A bee hug, a heart held close, a flowery bow: four illustrated ways of saying “I’m rather fond of you, you know”.",
    },
    image: {
      src: img("quatre-petits-coeurs").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Quatre vignettes d’abeilles aquarellées : abeille aux fleurs, deux abeilles qui s’enlacent, abeille au cœur rose, abeille toute ronde",
        en: "Four watercolour bee vignettes: a bee with flowers, two hugging bees, a bee holding a pink heart, a perfectly round bee",
      },
      background: "#FFFDF6",
      placeholder: true,
    },
    collections: ["la-vie-en-rose"],
    celebrations: ["amour", "amitie"],
    tags: [
      { fr: "amour", en: "love" },
      { fr: "amitié", en: "friendship" },
      { fr: "câlin", en: "hug" },
      { fr: "cœur", en: "heart" },
    ],
    featured: false,
    featuredOrder: null,
    personalizationTemplateId: "douceur",
    productSlugs: ALL_SUPPORTS,
    status: "published",
  },
  {
    id: "ill-abeilles-happy-birthday",
    slug: "abeilles-happy-birthday",
    title: { fr: "La Ronde des anniversaires", en: "The Birthday Round" },
    description: {
      fr: "Toute la ruche s’est mise sur son trente-et-un : gâteaux, confettis et cadeaux pour souhaiter les anniversaires en fanfare feutrée.",
      en: "The whole hive is dressed up: cakes, confetti and gifts to celebrate birthdays with the gentlest of fanfares.",
    },
    image: {
      src: img("abeilles-happy-birthday").full,
      width: 2048,
      height: 2048,
      alt: {
        fr: "Planche d’abeilles aquarellées fêtant des anniversaires avec gâteaux, cadeaux, confettis et messages « Happy Birthday »",
        en: "Sheet of watercolour bees celebrating birthdays with cakes, gifts, confetti and “Happy Birthday” lettering",
      },
      background: "#FFFFFF",
      placeholder: true,
    },
    collections: ["la-vie-en-jaune"],
    celebrations: ["anniversaire"],
    tags: [
      { fr: "anniversaire", en: "birthday" },
      { fr: "confettis", en: "confetti" },
      { fr: "cadeau", en: "gift" },
      { fr: "planche", en: "sheet" },
    ],
    featured: false,
    featuredOrder: null,
    personalizationTemplateId: "anniversaire",
    productSlugs: ["stickers", "affiche", "carte"],
    status: "published",
  },
];
